### ISSUE TITLE
Velocity inlet, periodic BC's

### ISSUE THREAD

**Issue by btweinstein** [latticeboltzmann/2d-lb#12]
1. Python
2. Cython
3. GPU

**Comment by matheuscfernandes** [comment]
Part 1: done

**Comment by matheuscfernandes** [comment]
Part 2: done

**Comment by btweinstein** [comment]
@matheuscfernandes How close are you to having things in opencl? We can work together on that today if you want, as that's an important step for making the videos.

**Comment by matheuscfernandes** [comment]
I am still making progress on creating the Kernels... I always struggle with these things. But it is definitely coming along. I am open to working together if you would like to do that!

**Comment by btweinstein** [comment]
Ok, I'll be working on this all day. If you could come to the lab that would be cool, as I need my desktop and it's immobile!

**Comment by matheuscfernandes** [comment]
I will come over a bit later if that's all right. I have a dual screen in my office and it is quite convenient for coding. But once i have all of the code written and just need to debug, I will come over. I am working on it slowly to avoid as many bugs as possible... as debugging is the bane to my existence.

**Comment by btweinstein** [comment]
Yeah debugging opencl is tough. Just keep me updated.

**Comment by matheuscfernandes** [comment]
Will do. For now I will work here, grab some lunch and see where I am at. I will text you before coming over.

**Comment by matheuscfernandes** [comment]
one problem I cannot figure out how to do easily in OpenCL... for the periodic BC I need a value of f that is at a different location. I think because of this we may need to implement some buffers, do you have any other suggestions?

**Comment by btweinstein** [comment]
All you have to do is, using correct indexing, grab the desired nonlocal
value.

**Comment by matheuscfernandes** [comment]
But what if the thread has not computed that value...

**Comment by btweinstein** [comment]
You may have to create a new 1d kernel or something that operates on the
top & bottom simultaneously.

**Comment by btweinstein** [comment]
Also I think I know how to fix your problem if you want to hang out.

**Comment by matheuscfernandes** [comment]
Sure, do you want me to come over now?

**Comment by matheuscfernandes** [comment]
I am all done with writing the meat of the code, now just need to debug and get it to do what we want it to do.

**Comment by btweinstein** [comment]
Yeah definitely. I just saw vortex sheets off the cylinder! So we can decide on what movie to make too.

**Comment by matheuscfernandes** [comment]
Part 3: done
