### ISSUE TITLE
OpenCL Obstacles

### ISSUE THREAD

**Issue by btweinstein** [latticeboltzmann/2d-lb#13]

**Comment by matheuscfernandes** [comment]
@btweinstein do you have the obstacles working at all yet? Is the python Pipe_Flow_Obstacles supposed to be working? If so, I cannot for some reason get it to run... I am calling it as if I were to call the normal Pipe_Flow and not passing the obstacle_mask. Do you have something somewhere defined to make the obstacle mask?

**Comment by matheuscfernandes** [comment]
The reason I am asking is that I am playing around and ran into this problem...

**Comment by btweinstein** [comment]
If you don't pass an obstacle mask, there are no obstacles, and the obstacle code will get very confused. To see the obstacles in action, run the obstacles_04 or obstacles_03 ipython notebooks.

**Comment by matheuscfernandes** [comment]
Cool, will do! Thanks.
